import type { PrintAreaInput } from "./variants";

/**
 * Mẫu LOẠI SẢN PHẨM in được (ngoài quần áo) – admin bấm tạo nhanh trong CMS.
 * ⚠️ Kích thước / DPI / viền tràn là SỐ LIỆU THAM KHẢO phổ biến trên thị trường, KHÔNG phải thông số xưởng.
 * Sản phẩm tạo ra ở trạng thái ẨN – admin phải đối chiếu thông số xưởng, nhập giá rồi mới bật bán.
 */
export type ProductTypePreset = {
  key: string;
  label: string;
  group: "Tranh & giấy" | "Cờ & phông" | "Cốc, bình, ốp" | "Nhà cửa";
  name: string;
  description: string;
  material: string;
  printMethod: string;
  weightGram: number;
  productionDays: string;
  sizes: string[];
  colors: { name: string; hex: string }[];
  image: string;
  areas: PrintAreaInput[];
};

const IMG = (k: string) => `/shapes/pt/${k}.svg`;
const WHITE = [{ name: "Trắng", hex: "#ffffff" }];

type AreaOpts = Partial<PrintAreaInput> & Pick<PrintAreaInput, "key" | "name" | "widthMm" | "heightMm" | "dpi" | "zoneX" | "zoneY" | "zoneW" | "zoneH">;
const area = (k: string, o: AreaOpts, mask = true, overlay = true): PrintAreaInput => ({
  bleedMm: 0,
  safeMm: 0,
  sizeSpecs: {},
  tips: "",
  warp: "",
  extraPrice: 0,
  mockupImage: IMG(k),
  maskImage: mask ? `/shapes/pt/${k}-mask.svg` : "",
  overlayImage: overlay ? `/shapes/pt/${k}-overlay.svg` : "",
  ...o,
});

const spec = (entries: [string, number, number][]) => Object.fromEntries(entries.map(([s, w, h]) => [s, { widthMm: w, heightMm: h }]));


export const PRODUCT_TYPE_PRESETS: ProductTypePreset[] = [
  {
    key: "canvas",
    label: "Tranh canvas",
    group: "Tranh & giấy",
    name: "Tranh canvas in ảnh theo yêu cầu",
    description: "Tranh canvas căng khung gỗ, in ảnh gia đình, ảnh cưới, tranh trang trí theo thiết kế của bạn. Mép tranh được bọc quanh khung.",
    material: "Vải canvas, khung gỗ thông",
    printMethod: "In phun kỹ thuật số",
    weightGram: 900,
    productionDays: "2–4 ngày",
    sizes: ["30x40cm", "40x60cm", "60x90cm"],
    colors: WHITE,
    image: IMG("canvas"),
    areas: [
      area("canvas", {
        key: "front",
        name: "Mặt tranh",
        widthMm: 660,
        heightMm: 960,
        dpi: 150,
        bleedMm: 30,
        safeMm: 10,
        sizeSpecs: spec([
          ["30x40cm", 360, 460],
          ["40x60cm", 460, 660],
          ["60x90cm", 660, 960],
        ]),
        tips: "Phần ngoài đường đỏ sẽ bọc quanh cạnh khung – kéo ảnh phủ kín tới mép ngoài, giữ khuôn mặt/chữ trong đường xanh.",
        zoneX: 0.28,
        zoneY: 0.13,
        zoneW: 0.44,
        zoneH: 0.64,
      }),
    ],
  },
  {
    key: "poster",
    label: "Poster",
    group: "Tranh & giấy",
    name: "Poster in ảnh theo yêu cầu",
    description: "Poster giấy dày in sắc nét, dán tường, làm quà hoặc trang trí sự kiện.",
    material: "Giấy couche 250gsm",
    printMethod: "In kỹ thuật số",
    weightGram: 150,
    productionDays: "1–2 ngày",
    sizes: ["A4", "A3", "A2"],
    colors: WHITE,
    image: IMG("poster"),
    areas: [
      area("poster", {
        key: "front",
        name: "Mặt in",
        widthMm: 426,
        heightMm: 600,
        dpi: 300,
        bleedMm: 3,
        safeMm: 5,
        sizeSpecs: spec([
          ["A4", 216, 303],
          ["A3", 303, 426],
          ["A2", 426, 600],
        ]),
        zoneX: 0.3174,
        zoneY: 0.2374,
        zoneW: 0.3651,
        zoneH: 0.5143,
      }),
    ],
  },
  {
    key: "calendar",
    label: "Lịch treo tường",
    group: "Tranh & giấy",
    name: "Lịch treo tường 13 tờ in ảnh",
    description: "Lịch treo tường khổ A4 ngang: 1 tờ bìa + 12 tháng, mỗi tháng 1 ảnh của bạn, lịch dương và âm lịch.",
    material: "Giấy couche 250gsm, gáy lò xo",
    printMethod: "In kỹ thuật số",
    weightGram: 450,
    productionDays: "3–5 ngày",
    sizes: ["A4 ngang"],
    colors: WHITE,
    image: IMG("calendar"),
    areas: [
      area("calendar", { key: "cover", name: "Bìa", widthMm: 303, heightMm: 216, dpi: 300, bleedMm: 3, safeMm: 6, zoneX: 0.2348, zoneY: 0.3248, zoneW: 0.5305, zoneH: 0.3782, tips: "Bìa lịch: ảnh đẹp nhất + tên gia đình/công ty." }),
      ...Array.from({ length: 12 }, (_, i) =>
        area("calendar", {
          key: `m${String(i + 1).padStart(2, "0")}`,
          name: `Tháng ${i + 1}`,
          widthMm: 303,
          heightMm: 216,
          dpi: 300,
          bleedMm: 3,
          safeMm: 6,
          zoneX: 0.2348,
          zoneY: 0.3248,
          zoneW: 0.5305,
          zoneH: 0.3782,
          tips: i === 0 ? "Đặt ảnh ở nửa trên, rồi vào công cụ Lịch → “Cả năm” để thêm lịch 12 tháng vào nửa dưới." : "",
        }),
      ),
    ],
  },
  {
    key: "flag",
    label: "Cờ",
    group: "Cờ & phông",
    name: "Cờ in theo yêu cầu",
    description: "Cờ vải in logo, cờ đội nhóm, cờ cổ vũ, cờ lớp. Mép cờ may viền chắc chắn.",
    material: "Vải polyester",
    printMethod: "In chuyển nhiệt",
    weightGram: 200,
    productionDays: "1–3 ngày",
    sizes: ["60x90cm", "90x150cm", "120x180cm"],
    colors: WHITE,
    image: IMG("flag"),
    areas: [
      area("flag", {
        key: "front",
        name: "Mặt cờ",
        widthMm: 1820,
        heightMm: 1220,
        dpi: 100,
        bleedMm: 10,
        safeMm: 20,
        sizeSpecs: spec([
          ["60x90cm", 920, 620],
          ["90x150cm", 1520, 920],
          ["120x180cm", 1820, 1220],
        ]),
        tips: "Mép cờ được may viền – chữ, logo nên cách mép ít nhất 3 cm (trong đường xanh).",
        zoneX: 0.1663,
        zoneY: 0.1963,
        zoneW: 0.6673,
        zoneH: 0.4473,
      }),
    ],
  },
  {
    key: "backdrop",
    label: "Backdrop",
    group: "Cờ & phông",
    name: "Backdrop sự kiện in theo yêu cầu",
    description: "Phông nền chụp ảnh sự kiện, sinh nhật, khai trương, hội nghị.",
    material: "Vải/bạt Hiflex",
    printMethod: "In khổ lớn",
    weightGram: 1500,
    productionDays: "1–2 ngày",
    sizes: ["2x2m", "3x2m", "3x2.5m"],
    colors: WHITE,
    image: IMG("backdrop"),
    areas: [
      area("backdrop", {
        key: "front",
        name: "Mặt phông",
        widthMm: 3040,
        heightMm: 2540,
        dpi: 72,
        bleedMm: 20,
        safeMm: 50,
        sizeSpecs: spec([
          ["2x2m", 2040, 2040],
          ["3x2m", 3040, 2040],
          ["3x2.5m", 3040, 2540],
        ]),
        tips: "Khổ lớn nhìn từ xa: 72 DPI là đủ nét. Chữ nên to, đặt ở 2/3 phía trên (phía dưới dễ bị người đứng che).",
        zoneX: 0.1555,
        zoneY: 0.1455,
        zoneW: 0.6891,
        zoneH: 0.5757,
      }),
    ],
  },
  {
    key: "mug",
    label: "Cốc sứ",
    group: "Cốc, bình, ốp",
    name: "Cốc sứ in hình 330ml",
    description: "Cốc sứ trắng in ảnh, in tên, quà tặng sinh nhật, kỷ niệm, quà doanh nghiệp. Dùng được máy rửa bát (tuỳ loại sứ).",
    material: "Sứ trắng tráng phủ",
    printMethod: "In chuyển nhiệt",
    weightGram: 400,
    productionDays: "1–2 ngày",
    sizes: ["330ml"],
    colors: WHITE,
    image: IMG("mug"),
    areas: [
      area("mug", {
        key: "wrap",
        name: "Dải in quanh cốc",
        widthMm: 200,
        heightMm: 85,
        dpi: 300,
        bleedMm: 2,
        safeMm: 5,
        warp: "cylinder",
        tips: "Dải in cuộn quanh thân cốc. Nửa trái/phải của dải là 2 mặt bên, phần sát 2 mép nằm gần tay cầm.",
        zoneX: 0.28,
        zoneY: 0.322,
        zoneW: 0.36,
        zoneH: 0.376,
      }),
    ],
  },
  {
    key: "bottle",
    label: "Bình giữ nhiệt",
    group: "Cốc, bình, ốp",
    name: "Bình giữ nhiệt in hình 500ml",
    description: "Bình giữ nhiệt inox in tên, logo, hình ảnh theo yêu cầu.",
    material: "Inox 304 phủ sơn tĩnh điện",
    printMethod: "In UV / chuyển nhiệt",
    weightGram: 450,
    productionDays: "2–3 ngày",
    sizes: ["500ml"],
    colors: WHITE,
    image: IMG("bottle"),
    areas: [
      area("bottle", {
        key: "wrap",
        name: "Dải in quanh bình",
        widthMm: 230,
        heightMm: 160,
        dpi: 300,
        bleedMm: 2,
        safeMm: 6,
        warp: "cylinder",
        zoneX: 0.38,
        zoneY: 0.28,
        zoneW: 0.24,
        zoneH: 0.526,
      }),
    ],
  },
  {
    key: "phonecase",
    label: "Ốp điện thoại",
    group: "Cốc, bình, ốp",
    name: "Ốp điện thoại in hình theo yêu cầu",
    description: "Ốp lưng in ảnh, in tên theo từng dòng máy. Chọn đúng dòng máy khi đặt.",
    material: "Nhựa dẻo TPU / cứng PC",
    printMethod: "In UV",
    weightGram: 60,
    productionDays: "1–2 ngày",
    sizes: ["iPhone 15", "iPhone 15 Pro Max", "Samsung S24"],
    colors: WHITE,
    image: IMG("phonecase"),
    areas: [
      area("phonecase", {
        key: "back",
        name: "Mặt lưng",
        widthMm: 84,
        heightMm: 166,
        dpi: 300,
        bleedMm: 2,
        safeMm: 5,
        sizeSpecs: spec([
          ["iPhone 15", 78, 155],
          ["iPhone 15 Pro Max", 84, 166],
          ["Samsung S24", 76, 153],
        ]),
        tips: "Góc trên bên trái là lỗ camera – không đặt chữ, khuôn mặt ở đó.",
        zoneX: 0.33,
        zoneY: 0.12,
        zoneW: 0.34,
        zoneH: 0.672,
      }),
    ],
  },
  {
    key: "pillow",
    label: "Gối vuông",
    group: "Nhà cửa",
    name: "Gối vuông in hình 2 mặt",
    description: "Gối tựa sofa in ảnh 2 mặt, kèm ruột gối bông.",
    material: "Vải polyester mềm, ruột bông",
    printMethod: "In chuyển nhiệt",
    weightGram: 500,
    productionDays: "2–3 ngày",
    sizes: ["40x40cm", "45x45cm"],
    colors: WHITE,
    image: IMG("pillow"),
    areas: (["front", "back"] as const).map((k) =>
      area("pillow", {
        key: k,
        name: k === "front" ? "Mặt trước" : "Mặt sau",
        widthMm: 480,
        heightMm: 480,
        dpi: 150,
        bleedMm: 15,
        safeMm: 25,
        sizeSpecs: spec([
          ["40x40cm", 430, 430],
          ["45x45cm", 480, 480],
        ]),
        tips: k === "front" ? "Mép gối được may lộn vào trong – giữ nội dung quan trọng trong đường xanh. Có thể chép thiết kế sang mặt sau." : "",
        zoneX: 0.2013,
        zoneY: 0.2013,
        zoneW: 0.5973,
        zoneH: 0.5973,
      }),
    ),
  },
  {
    key: "blanket",
    label: "Chăn nỉ",
    group: "Nhà cửa",
    name: "Chăn nỉ in hình theo yêu cầu",
    description: "Chăn nỉ mềm in ảnh gia đình, thú cưng, quà tặng.",
    material: "Nỉ lông cừu",
    printMethod: "In chuyển nhiệt",
    weightGram: 1200,
    productionDays: "3–4 ngày",
    sizes: ["120x150cm", "150x200cm"],
    colors: WHITE,
    image: IMG("blanket"),
    areas: [
      area("blanket", {
        key: "front",
        name: "Mặt chăn",
        widthMm: 1540,
        heightMm: 2040,
        dpi: 100,
        bleedMm: 20,
        safeMm: 40,
        sizeSpecs: spec([
          ["120x150cm", 1240, 1540],
          ["150x200cm", 1540, 2040],
        ]),
        zoneX: 0.2536,
        zoneY: 0.1736,
        zoneW: 0.4928,
        zoneH: 0.6528,
      }),
    ],
  },
  {
    key: "rug",
    label: "Thảm",
    group: "Nhà cửa",
    name: "Thảm in hình theo yêu cầu",
    description: "Thảm trải sàn, thảm chùi chân in logo, hình ảnh. Đế cao su chống trượt.",
    material: "Nỉ đế cao su",
    printMethod: "In chuyển nhiệt",
    weightGram: 1500,
    productionDays: "3–4 ngày",
    sizes: ["60x90cm", "120x180cm"],
    colors: WHITE,
    image: IMG("rug"),
    areas: [
      area("rug", {
        key: "front",
        name: "Mặt thảm",
        widthMm: 1820,
        heightMm: 1220,
        dpi: 100,
        bleedMm: 10,
        safeMm: 20,
        sizeSpecs: spec([
          ["60x90cm", 920, 620],
          ["120x180cm", 1820, 1220],
        ]),
        zoneX: 0.1663,
        zoneY: 0.2563,
        zoneW: 0.6673,
        zoneH: 0.4473,
      }),
    ],
  },
  {
    key: "curtain",
    label: "Rèm cửa",
    group: "Nhà cửa",
    name: "Rèm cửa in hình (1 tấm)",
    description: "Rèm cửa in hình phong cảnh, hoạ tiết theo yêu cầu. Giá tính theo 1 tấm.",
    material: "Vải polyester dày",
    printMethod: "In chuyển nhiệt",
    weightGram: 1000,
    productionDays: "3–5 ngày",
    sizes: ["140x250cm"],
    colors: WHITE,
    image: IMG("curtain"),
    areas: [
      area("curtain", {
        key: "front",
        name: "Mặt rèm",
        widthMm: 1500,
        heightMm: 2600,
        dpi: 72,
        bleedMm: 50,
        safeMm: 80,
        tips: "Phần trên cùng may luồn thanh treo – không đặt nội dung quan trọng sát mép trên.",
        zoneX: 0.3071,
        zoneY: 0.1271,
        zoneW: 0.3857,
        zoneH: 0.6686,
      }),
    ],
  },
];
